spring.application.name=ProyectoS1_Julian

#Configuracion de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db
spring.datasource.username=root
spring.datasource.password=1097100290

#Cofiguracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true